ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS email VARCHAR(255) UNIQUE;
ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS reset_token VARCHAR(255);
ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS reset_token_expires TIMESTAMPTZ;
ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
