ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS plan_code VARCHAR(20) DEFAULT NULL;
ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS paddle_subscription_id VARCHAR(100) DEFAULT NULL;
ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS plan_start_date DATE DEFAULT NULL;
ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS plan_renewal_date DATE DEFAULT NULL;
ALTER TABLE dw_user ADD COLUMN IF NOT EXISTS using_grace_slot BOOLEAN NOT NULL DEFAULT false;
